name: SA
title: Santiago Archila
description: "Santiago Archila - Software Engineer | Neuroscientist"
url: "http://localhost:4000"

port: 4000
pygments: true

permalink: /:year/:month/:day/:title.html
markdown: redcarpet

owner:
  name: Santiago Archila
  twitter: tweetmeSanti
